client/src/App.js
client/src/Canvas.js
client/src/Home.css
client/src/Home.js
client/src/Main.js
client/src/index.js

This is the basic UI for the home screen. Currently the login button is hard-coded to lead straight to the dashboard.

Home Screen Prototype 

---

client/package.json
client/src/Banner.css
client/src/Banner.js
client/src/Dashboard.js

This is the basic UI for the navbar. The log out button is hard-coded to return to the home screen

Navbar Prototype

---

client/src/Canvas.js
client/src/Dashboard.css
client/src/Dashboard.js
client/src/GameSelector.css
client/src/GameSelector.js

Basic UI for the dashboard completed with this pull request. The game selector displays hard-coded information and links to a game screen.

Complete dashboard prototype

---

client/package.json
client/public/manifest.json
client/src/Canvas.js
client/src/Home.js
client/src/firebase.js
client/src/index.js
client/src/signedUploadUrl.js

- tried to create image upload URL but that failed, waiting for service account key permissions
- configure firebase in its own file so every component can access initialized instance easily
- read game data from firestore
- update game data in firestore when player sends image (for now, no image is uploaded, but the game state is changed)
- some TODOs for image upload or user auth dependency, some TODOs for edge case checks that I will do soon. But the basic functionality is present.

Canvas gets game data from database

---

client/src/App.js
client/src/Home.js
client/src/Session/context.js
client/src/Session/index.js
client/src/Session/withAuthentication.js
client/src/index.js

- implement session handling through higher-order component
- integrate Firebase context into website 
- clean up code and insert buttons where needed

Implement session handling and Firebase context

---

api/src/main/java/com/google/sps/Application.java
api/src/main/java/com/google/sps/SignedUpload.java
client/client.yml

- fix routing in deployment
- [feel free to check the app, redeployed](http://phoebeliang-step.appspot.com/)
- fix style (indentation, extraneous code)

Fix dispatch files

---

client/src/Account/index.js
client/src/Canvas.js
client/src/Dashboard.js
client/src/Firebase/Firebase.js
client/src/Home.js
client/src/Session/index.js
client/src/Session/withAuthentication.js
client/src/Session/withAuthorization.js
client/src/Session/withEmailVerification.js
client/src/SignUp/index.js

- require email verification to access account specific pages

Email Verification

---

client/src/Account/index.js
client/src/SignUp/index.js

- change form placeholder to username instead of full name
- add button to return to dashboard on account page

Small fixes

---

client/src/components/Account/index.js
client/src/components/Dashboard/index.js
client/src/components/SignIn/index.js
client/src/components/SignUp/index.js
client/src/constants/routes.js

- implement code to fetch user data from the database

Fetch data from database

---

client/src/components/Account/index.js
client/src/components/App/index.js
client/src/components/Banner/index.js
client/src/components/Dashboard/index.js
client/src/components/Firebase/Firebase.js
client/src/components/GameSelector/GameSelector.css
client/src/components/GameSelector/index.js
client/src/components/SignIn/index.js
client/src/components/SignUp/index.js
client/src/constants/routes.js

- implement database info retrieval without listeners
- fix dashboard routing so that the url is just '/dashboard', preventing users from accessing other users' data by changing the url

Populate dashboard with database info

---

client/src/components/App/index.js
client/src/components/CreateGame/index.js
client/src/components/Dashboard/index.js
client/src/components/Firebase/Firebase.js
client/src/components/GameSelector/index.js
client/src/components/SignUp/index.js
client/src/constants/routes.js

- host game button now leads to a form that lets the user enter a name for the game
- submitting the form generates a game entity on the Firestore database and adds the user as a player 
- the user's own game list is also updated with the new game's id
- the game id is displayed to the user so that they can share it

Implement game creation

---

client/src/components/App/index.js
client/src/components/Dashboard/index.js
client/src/components/Firebase/Firebase.js
client/src/components/JoinGame/index.js
client/src/components/SignUp/index.js
client/src/constants/routes.js

- users can join a game by entering a game ID provided by someone else

Implement basic game joining

---

client/src/components/App/index.js
client/src/components/Game/Canvas.js
client/src/components/Game/index.js
client/src/components/GameSelector/index.js

game code has been refactored to use user ID instead of username

Refactor ingame behavior

---

client/src/components/CreateGame/index.js
client/src/components/Firebase/Firebase.js
client/src/components/GameSelector/index.js
client/src/components/JoinGame/index.js
client/src/components/SignUp/index.js

- game cards now show more information based on whether the game has ended or hasn't started, including the number of turns a user has to wait until their turn
- trying to join a game that a user is already in now displays a warning and does not initiate the joining operation 
- similar warnings implemented if a user tries to join a game that has already ended
- the app now redirects to the game page after a user joins a game
- game creation has more options

Frontend fixes

---

client/src/components/CreateGame/index.js
client/src/components/Firebase/Firebase.js
client/src/components/Game/index.js
client/src/components/SignIn/index.js

- Fixes #34 
- Add some autocomplete form elements for better accessibility

fix small bugs

---

client/src/components/Game/Canvas.js
client/src/components/Game/Endgame.js
client/src/components/Game/FabricCanvas.js
client/src/components/GameSelector/index.js

- All image downloads from GCS are now done through signed URL
- Small wording in game card changed so it displays `0 player(s) to go` instead of `0 player to go`
Fixes #31 as well as the image collage download failure in #53 
After this branch is merged, you will need to start up the back end to view any image in the game page.

Anonymous image viewing

---

client/src/components/GameSelector/index.js

- when it was the current user's turn, the turn indicator would say "0 player until your turn!" instead of "It's your turn to play!"

Fix current turn indicator issue.

---

validate-upload.go

- This file is already deployed and running on Cloud Functions, just adding here to leave a record of the code. Adding to the repo will not change any existing behavior.
- Written in Golang because the [tutorial for image upload validation](https://cloud.google.com/blog/products/storage-data-transfer/uploading-images-directly-to-cloud-storage-by-using-signed-url) was Golang. Added additional Firestore capability on top of the tutorial example.

add cloud function file

---

client/src/components/App/index.js
client/src/components/CreateGame/CreateGame.css
client/src/components/CreateGame/index.js
client/src/components/Dashboard/index.js
client/src/components/Firebase/Firebase.js
client/src/components/Game/Canvas.js
client/src/components/GameSelector/index.js
client/src/components/JoinGame/JoinGame.css
client/src/components/JoinGame/index.js
client/src/constants/routes.js

- the create game and join game forms are now in the form of a modal dialog window instead of a separate page
closes #62

Modal dialog windows

---

api/src/main/java/com/google/sps/ValidateUsername.java
client/client.yml
client/src/components/App/App.css
client/src/components/Game/Canvas.js
client/src/components/Game/Endgame.js
client/src/components/Game/FabricCanvas.js
client/src/components/Game/FabricContextProvider.js
client/src/components/Game/Game.css
client/src/components/Game/index.js
client/src/components/SignUp/index.js

- No changes in terms of function, only cosmetic + deployment settings.
- Add https to website
- Fix some deployment-specific issues
- Add bootstrap styling to Canvas and Endgame components
None

Stylized game components

---

client/src/components/Session/withEmailVerification.js
client/src/components/SignUp/index.js

Instead of rerouting to the landing page after signing up, the user is automatically logged in and rerouted to the dashboard.

Automatically sign in after signing up.
